<a href="https://colab.research.google.com/github/raghavx/tensorflow/blob/tf-2.9.2/01_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [47]:
X = tf.constant([1.0,2.0,3.0,4.0,5.0,6.0,2.0,3.0,4.0,5.0,6.0])
y = tf.constant([11.0,12.0,13.0,14.0,15.0,16.0,12.0,13.0,14.0,15.0,16.0])
X,y

(<tf.Tensor: shape=(11,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 2., 3., 4., 5., 6.], dtype=float32)>,
 <tf.Tensor: shape=(11,), dtype=float32, numpy=
 array([11., 12., 13., 14., 15., 16., 12., 13., 14., 15., 16.],
       dtype=float32)>)

In [48]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(50, activation=None))
model.add(tf.keras.layers.Dense(1, activation=None))
model.compile(loss="mae" ,optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), metrics=["mae"])
model.fit(x=tf.expand_dims(X, axis=-1),y=y,epochs=100)



Epoch 1/100
1/1 [==============================] - 0s 396ms/step - loss: 13.2797 - mae: 13.2797
Epoch 2/100
1/1 [==============================] - 0s 10ms/step - loss: 12.5613 - mae: 12.5613
Epoch 3/100
1/1 [==============================] - 0s 9ms/step - loss: 11.8396 - mae: 11.8396
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 11.1136 - mae: 11.1136
Epoch 5/100
1/1 [==============================] - 0s 12ms/step - loss: 10.3815 - mae: 10.3815
Epoch 6/100
1/1 [==============================] - 0s 10ms/step - loss: 9.6407 - mae: 9.6407
Epoch 7/100
1/1 [==============================] - 0s 12ms/step - loss: 8.8882 - mae: 8.8882
Epoch 8/100
1/1 [==============================] - 0s 11ms/step - loss: 8.1210 - mae: 8.1210
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 7.3358 - mae: 7.3358
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 6.5294 - mae: 6.5294
Epoch 11/100
1/1 [==============================] - 0s 14ms/s

In [49]:
model.predict([8.0])

1/1 [==============================] - 0s 65ms/step


array([[18.635426]], dtype=float32)